# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmJjNDgzNDA2YThkZTRiMDhlYWEyNmExMDFiNThiOGQ0MmFhNGQzOTZjOGViN2JhZTI3OTJjZTIzYjVmZjFhZGI2YmFjZWJmNjY0MjgzN2E4MmNiODlhMDY5NTFkMzRjZDU0MGZlMjBhNzg4NDdhNTAyOTc2MjA1ODg4OTAxYmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
