/*
 * Copyright (c) 2026 Saathratri, LLC. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-Saathratri-Proprietary
 * Proprietary and confidential - see LICENSE in the repository root.
 */

/**
 * This package file was generated by JHipster
 */
package com.saathratri.developer.cassandra.store.security.oauth2;
