@echo off
REM Start cassandrablog in dev mode: Spring Boot 'dev' profile + remote debug on port 18083.
REM Prereqs: infra (Keycloak, JHipster Registry, databases) must already be running.
REM Generated by generator-jhipster-orchestrator (spring-boot-orchestrator) - do not edit by hand.
cd /d "%~dp0"
call "%~dp0mvnw.cmd" spring-boot:run -Dspring-boot.run.profiles=dev "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=18083"
