package com.saathratri.developer.cassandra.store.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CassReportAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassReportAllPropertiesEquals(CassReport expected, CassReport actual) {
        assertCassReportAutoGeneratedPropertiesEquals(expected, actual);
        assertCassReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassReportAllUpdatablePropertiesEquals(CassReport expected, CassReport actual) {
        assertCassReportUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassReportAutoGeneratedPropertiesEquals(CassReport expected, CassReport actual) {
        assertThat(expected)
            .as("Verify CassReport auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassReportUpdatableFieldsEquals(CassReport expected, CassReport actual) {
        assertThat(expected).as("Verify CassReport relevant properties");
    }
}
