package com.saathratri.developer.cassandra.store.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CassProductAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassProductAllPropertiesEquals(CassProduct expected, CassProduct actual) {
        assertCassProductAutoGeneratedPropertiesEquals(expected, actual);
        assertCassProductAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassProductAllUpdatablePropertiesEquals(CassProduct expected, CassProduct actual) {
        assertCassProductUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassProductAutoGeneratedPropertiesEquals(CassProduct expected, CassProduct actual) {
        assertThat(expected)
            .as("Verify CassProduct auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassProductUpdatableFieldsEquals(CassProduct expected, CassProduct actual) {
        assertThat(expected).as("Verify CassProduct relevant properties");
    }
}
