#!/usr/bin/env bash
# Start psqlblog in dev mode: Spring Boot 'dev' profile + remote debug on port 18081.
# Prereqs: infra (Keycloak, JHipster Registry, databases) must already be running.
# Generated by generator-jhipster-orchestrator (spring-boot-orchestrator) - do not edit by hand.
cd "$(dirname "$0")"
exec ./mvnw spring-boot:run \
  -Dspring-boot.run.profiles=dev \
  -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=18081"
