#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTVmNTM4ZjMzNzEyZTJjZDg3NmJmOTA5ZWQ5NDY3MzI1MmIzZjFhYTA1ZDBkMzlhMjRhOWQ0NmQ5OWE0MWU5OTkwMDRlNjkwYjlkMDE0OGVmNTFiZGY4OGQ1MDAzYmRjZDFkNw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
