package com.saathratri.developer.psql.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PsqlTajUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTajUserAllPropertiesEquals(PsqlTajUser expected, PsqlTajUser actual) {
        assertPsqlTajUserAutoGeneratedPropertiesEquals(expected, actual);
        assertPsqlTajUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTajUserAllUpdatablePropertiesEquals(PsqlTajUser expected, PsqlTajUser actual) {
        assertPsqlTajUserUpdatableFieldsEquals(expected, actual);
        assertPsqlTajUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTajUserAutoGeneratedPropertiesEquals(PsqlTajUser expected, PsqlTajUser actual) {
        assertThat(actual)
            .as("Verify PsqlTajUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTajUserUpdatableFieldsEquals(PsqlTajUser expected, PsqlTajUser actual) {
        assertThat(actual)
            .as("Verify PsqlTajUser relevant properties")
            .satisfies(a -> assertThat(a.getLogin()).as("check login").isEqualTo(expected.getLogin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTajUserUpdatableRelationshipsEquals(PsqlTajUser expected, PsqlTajUser actual) {
        // empty method
    }
}
