package com.saathratri.developer.psql.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PsqlPostAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlPostAllPropertiesEquals(PsqlPost expected, PsqlPost actual) {
        assertPsqlPostAutoGeneratedPropertiesEquals(expected, actual);
        assertPsqlPostAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlPostAllUpdatablePropertiesEquals(PsqlPost expected, PsqlPost actual) {
        assertPsqlPostUpdatableFieldsEquals(expected, actual);
        assertPsqlPostUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlPostAutoGeneratedPropertiesEquals(PsqlPost expected, PsqlPost actual) {
        assertThat(actual)
            .as("Verify PsqlPost auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlPostUpdatableFieldsEquals(PsqlPost expected, PsqlPost actual) {
        assertThat(actual)
            .as("Verify PsqlPost relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlPostUpdatableRelationshipsEquals(PsqlPost expected, PsqlPost actual) {
        assertThat(actual)
            .as("Verify PsqlPost relationships")
            .satisfies(a -> assertThat(a.getBlog()).as("check blog").isEqualTo(expected.getBlog()))
            .satisfies(a -> assertThat(a.getTags()).as("check tags").isEqualTo(expected.getTags()));
    }
}
