package com.saathratri.developer.psql.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PsqlBlogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlBlogAllPropertiesEquals(PsqlBlog expected, PsqlBlog actual) {
        assertPsqlBlogAutoGeneratedPropertiesEquals(expected, actual);
        assertPsqlBlogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlBlogAllUpdatablePropertiesEquals(PsqlBlog expected, PsqlBlog actual) {
        assertPsqlBlogUpdatableFieldsEquals(expected, actual);
        assertPsqlBlogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlBlogAutoGeneratedPropertiesEquals(PsqlBlog expected, PsqlBlog actual) {
        assertThat(actual)
            .as("Verify PsqlBlog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlBlogUpdatableFieldsEquals(PsqlBlog expected, PsqlBlog actual) {
        assertThat(actual)
            .as("Verify PsqlBlog relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getHandle()).as("check handle").isEqualTo(expected.getHandle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlBlogUpdatableRelationshipsEquals(PsqlBlog expected, PsqlBlog actual) {
        assertThat(actual)
            .as("Verify PsqlBlog relationships")
            .satisfies(a -> assertThat(a.getTajUser()).as("check tajUser").isEqualTo(expected.getTajUser()));
    }
}
