package com.saathratri.developer.psql.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PsqlTagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTagAllPropertiesEquals(PsqlTag expected, PsqlTag actual) {
        assertPsqlTagAutoGeneratedPropertiesEquals(expected, actual);
        assertPsqlTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTagAllUpdatablePropertiesEquals(PsqlTag expected, PsqlTag actual) {
        assertPsqlTagUpdatableFieldsEquals(expected, actual);
        assertPsqlTagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTagAutoGeneratedPropertiesEquals(PsqlTag expected, PsqlTag actual) {
        assertThat(actual)
            .as("Verify PsqlTag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTagUpdatableFieldsEquals(PsqlTag expected, PsqlTag actual) {
        assertThat(actual)
            .as("Verify PsqlTag relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getNameEmbedding()).as("check nameEmbedding").isEqualTo(expected.getNameEmbedding()))
            .satisfies(a ->
                assertThat(a.getDescriptionEmbedding()).as("check descriptionEmbedding").isEqualTo(expected.getDescriptionEmbedding())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlTagUpdatableRelationshipsEquals(PsqlTag expected, PsqlTag actual) {
        assertThat(actual)
            .as("Verify PsqlTag relationships")
            .satisfies(a -> assertThat(a.getPosts()).as("check posts").isEqualTo(expected.getPosts()));
    }
}
