# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWQ5YWVkNDRhNDViZTMzODc3ZGFjYTRiNjk3MzQ1NzAwMzBmZWUzZDM0NGFhMmRiZTAxZTUyZDA3MmNmOTVhZDcxMmJkMmIzMmZlZjNiMGUwZDYzODgyYTNjMmUzNjgxYjExMzg0YjU4YjAxZjBjMTY1OGE1ZDAyZDA4YzczMDE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
