# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTMzYTJkOGQyMDVjMzlhMTE2YzA2NDEzMmE2NDk5YTM3MTk4OTlhZWU0YjhlNWRiODMwYTE5NDQwNjVlMTRiMDU5MTk2NTg2NzZmOTBlY2QzYzk3YjgyMDQ5MmNhZjBjZmNjOWJlYTljMjVlN2NjOGRjYWExYzJkN2UyNWE3ODU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
