package com.saathratri.developer.psql.store.domain;

import static com.saathratri.developer.psql.store.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PsqlProductAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlProductAllPropertiesEquals(PsqlProduct expected, PsqlProduct actual) {
        assertPsqlProductAutoGeneratedPropertiesEquals(expected, actual);
        assertPsqlProductAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlProductAllUpdatablePropertiesEquals(PsqlProduct expected, PsqlProduct actual) {
        assertPsqlProductUpdatableFieldsEquals(expected, actual);
        assertPsqlProductUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlProductAutoGeneratedPropertiesEquals(PsqlProduct expected, PsqlProduct actual) {
        assertThat(actual)
            .as("Verify PsqlProduct auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlProductUpdatableFieldsEquals(PsqlProduct expected, PsqlProduct actual) {
        assertThat(actual)
            .as("Verify PsqlProduct relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()))
            .satisfies(a -> assertThat(a.getImageContentType()).as("check image content type").isEqualTo(expected.getImageContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlProductUpdatableRelationshipsEquals(PsqlProduct expected, PsqlProduct actual) {
        // empty method
    }
}
