package com.saathratri.developer.psql.store.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PsqlReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlReportAllPropertiesEquals(PsqlReport expected, PsqlReport actual) {
        assertPsqlReportAutoGeneratedPropertiesEquals(expected, actual);
        assertPsqlReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlReportAllUpdatablePropertiesEquals(PsqlReport expected, PsqlReport actual) {
        assertPsqlReportUpdatableFieldsEquals(expected, actual);
        assertPsqlReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlReportAutoGeneratedPropertiesEquals(PsqlReport expected, PsqlReport actual) {
        assertThat(actual)
            .as("Verify PsqlReport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlReportUpdatableFieldsEquals(PsqlReport expected, PsqlReport actual) {
        assertThat(actual)
            .as("Verify PsqlReport relevant properties")
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFileExtension()).as("check fileExtension").isEqualTo(expected.getFileExtension()))
            .satisfies(a -> assertThat(a.getCreateDate()).as("check createDate").isEqualTo(expected.getCreateDate()))
            .satisfies(a -> assertThat(a.getFile()).as("check file").isEqualTo(expected.getFile()))
            .satisfies(a -> assertThat(a.getFileContentType()).as("check file content type").isEqualTo(expected.getFileContentType()))
            .satisfies(a -> assertThat(a.getApproved()).as("check approved").isEqualTo(expected.getApproved()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPsqlReportUpdatableRelationshipsEquals(PsqlReport expected, PsqlReport actual) {
        assertThat(actual)
            .as("Verify PsqlReport relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
