package com.saathratri.developer.cassandra.blog.domain;

import static com.saathratri.developer.cassandra.blog.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CassSaathratriEntity2Asserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity2AllPropertiesEquals(CassSaathratriEntity2 expected, CassSaathratriEntity2 actual) {
        assertCassSaathratriEntity2AutoGeneratedPropertiesEquals(expected, actual);
        assertCassSaathratriEntity2AllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity2AllUpdatablePropertiesEquals(
        CassSaathratriEntity2 expected,
        CassSaathratriEntity2 actual
    ) {
        assertCassSaathratriEntity2UpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity2AutoGeneratedPropertiesEquals(
        CassSaathratriEntity2 expected,
        CassSaathratriEntity2 actual
    ) {
        assertThat(expected)
            .as("Verify CassSaathratriEntity2 auto generated properties")
            .satisfies(e ->
                assertThat(e.getCompositeId().getEntityTypeId())
                    .as("check entityTypeId")
                    .isEqualTo(actual.getCompositeId().getEntityTypeId())
            )
            .satisfies(e ->
                assertThat(e.getCompositeId().getYearOfDateAdded())
                    .as("check yearOfDateAdded")
                    .isEqualTo(actual.getCompositeId().getYearOfDateAdded())
            )
            .satisfies(e ->
                assertThat(e.getCompositeId().getArrivalDate()).as("check arrivalDate").isEqualTo(actual.getCompositeId().getArrivalDate())
            )
            .satisfies(e -> assertThat(e.getCompositeId().getBlogId()).as("check blogId").isEqualTo(actual.getCompositeId().getBlogId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity2UpdatableFieldsEquals(CassSaathratriEntity2 expected, CassSaathratriEntity2 actual) {
        assertThat(expected)
            .as("Verify CassSaathratriEntity2 relevant properties")
            .satisfies(e -> assertThat(e.getEntityName()).as("check entityName").isEqualTo(actual.getEntityName()))
            .satisfies(e -> assertThat(e.getEntityDescription()).as("check entityDescription").isEqualTo(actual.getEntityDescription()))
            .satisfies(e ->
                assertThat(e.getEntityCost()).as("check entityCost").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getEntityCost())
            )
            .satisfies(e -> assertThat(e.getDepartureDate()).as("check departureDate").isEqualTo(actual.getDepartureDate()));
    }
}
