package com.saathratri.developer.cassandra.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CassBlogAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassBlogAllPropertiesEquals(CassBlog expected, CassBlog actual) {
        assertCassBlogAutoGeneratedPropertiesEquals(expected, actual);
        assertCassBlogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassBlogAllUpdatablePropertiesEquals(CassBlog expected, CassBlog actual) {
        assertCassBlogUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassBlogAutoGeneratedPropertiesEquals(CassBlog expected, CassBlog actual) {}

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassBlogUpdatableFieldsEquals(CassBlog expected, CassBlog actual) {
        assertThat(expected)
            .as("Verify CassBlog relevant properties")
            .satisfies(e -> assertThat(e.getHandle()).as("check handle").isEqualTo(actual.getHandle()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()));
    }
}
