package com.saathratri.developer.cassandra.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CassSaathratriEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntityAllPropertiesEquals(CassSaathratriEntity expected, CassSaathratriEntity actual) {
        assertCassSaathratriEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertCassSaathratriEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntityAllUpdatablePropertiesEquals(CassSaathratriEntity expected, CassSaathratriEntity actual) {
        assertCassSaathratriEntityUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntityAutoGeneratedPropertiesEquals(CassSaathratriEntity expected, CassSaathratriEntity actual) {
        assertThat(expected)
            .as("Verify CassSaathratriEntity auto generated properties")
            .satisfies(e -> assertThat(e.getEntityId()).as("check entityId").isEqualTo(actual.getEntityId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntityUpdatableFieldsEquals(CassSaathratriEntity expected, CassSaathratriEntity actual) {
        assertThat(expected).as("Verify CassSaathratriEntity relevant properties");
    }
}
