package com.saathratri.developer.cassandra.blog.domain;

import static com.saathratri.developer.cassandra.blog.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CassSaathratriEntity3Asserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity3AllPropertiesEquals(CassSaathratriEntity3 expected, CassSaathratriEntity3 actual) {
        assertCassSaathratriEntity3AutoGeneratedPropertiesEquals(expected, actual);
        assertCassSaathratriEntity3AllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity3AllUpdatablePropertiesEquals(
        CassSaathratriEntity3 expected,
        CassSaathratriEntity3 actual
    ) {
        assertCassSaathratriEntity3UpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity3AutoGeneratedPropertiesEquals(
        CassSaathratriEntity3 expected,
        CassSaathratriEntity3 actual
    ) {}

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity3UpdatableFieldsEquals(CassSaathratriEntity3 expected, CassSaathratriEntity3 actual) {
        assertThat(expected)
            .as("Verify CassSaathratriEntity3 relevant properties")
            .satisfies(e -> assertThat(e.getEntityName()).as("check entityName").isEqualTo(actual.getEntityName()))
            .satisfies(e -> assertThat(e.getEntityDescription()).as("check entityDescription").isEqualTo(actual.getEntityDescription()))
            .satisfies(e ->
                assertThat(e.getEntityCost()).as("check entityCost").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getEntityCost())
            )
            .satisfies(e -> assertThat(e.getDepartureDate()).as("check departureDate").isEqualTo(actual.getDepartureDate()))
            .satisfies(e -> assertThat(e.getTags()).as("check tags").isEqualTo(actual.getTags()));
    }
}
