package com.saathratri.developer.cassandra.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CassLandingPageByOrganizationAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassLandingPageByOrganizationAllPropertiesEquals(
        CassLandingPageByOrganization expected,
        CassLandingPageByOrganization actual
    ) {
        assertCassLandingPageByOrganizationAutoGeneratedPropertiesEquals(expected, actual);
        assertCassLandingPageByOrganizationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassLandingPageByOrganizationAllUpdatablePropertiesEquals(
        CassLandingPageByOrganization expected,
        CassLandingPageByOrganization actual
    ) {
        assertCassLandingPageByOrganizationUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassLandingPageByOrganizationAutoGeneratedPropertiesEquals(
        CassLandingPageByOrganization expected,
        CassLandingPageByOrganization actual
    ) {
        assertThat(expected)
            .as("Verify CassLandingPageByOrganization auto generated properties")
            .satisfies(e -> assertThat(e.getOrganizationId()).as("check organizationId").isEqualTo(actual.getOrganizationId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassLandingPageByOrganizationUpdatableFieldsEquals(
        CassLandingPageByOrganization expected,
        CassLandingPageByOrganization actual
    ) {
        assertThat(expected).as("Verify CassLandingPageByOrganization relevant properties");
    }
}
