package com.saathratri.developer.cassandra.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CassTajUserAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassTajUserAllPropertiesEquals(CassTajUser expected, CassTajUser actual) {
        assertCassTajUserAutoGeneratedPropertiesEquals(expected, actual);
        assertCassTajUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassTajUserAllUpdatablePropertiesEquals(CassTajUser expected, CassTajUser actual) {
        assertCassTajUserUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassTajUserAutoGeneratedPropertiesEquals(CassTajUser expected, CassTajUser actual) {
        assertThat(expected)
            .as("Verify CassTajUser auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassTajUserUpdatableFieldsEquals(CassTajUser expected, CassTajUser actual) {
        assertThat(expected).as("Verify CassTajUser relevant properties");
    }
}
