package com.saathratri.developer.cassandra.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CassSaathratriEntity4Asserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity4AllPropertiesEquals(CassSaathratriEntity4 expected, CassSaathratriEntity4 actual) {
        assertCassSaathratriEntity4AutoGeneratedPropertiesEquals(expected, actual);
        assertCassSaathratriEntity4AllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity4AllUpdatablePropertiesEquals(
        CassSaathratriEntity4 expected,
        CassSaathratriEntity4 actual
    ) {
        assertCassSaathratriEntity4UpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity4AutoGeneratedPropertiesEquals(
        CassSaathratriEntity4 expected,
        CassSaathratriEntity4 actual
    ) {
        assertThat(expected)
            .as("Verify CassSaathratriEntity4 auto generated properties")
            .satisfies(e ->
                assertThat(e.getCompositeId().getOrganizationId())
                    .as("check organizationId")
                    .isEqualTo(actual.getCompositeId().getOrganizationId())
            )
            .satisfies(e ->
                assertThat(e.getCompositeId().getAttributeKey())
                    .as("check attributeKey")
                    .isEqualTo(actual.getCompositeId().getAttributeKey())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSaathratriEntity4UpdatableFieldsEquals(CassSaathratriEntity4 expected, CassSaathratriEntity4 actual) {
        assertThat(expected)
            .as("Verify CassSaathratriEntity4 relevant properties")
            .satisfies(e -> assertThat(e.getAttributeValue()).as("check attributeValue").isEqualTo(actual.getAttributeValue()));
    }
}
