package com.saathratri.developer.cassandra.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CassSetEntityByOrganizationAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSetEntityByOrganizationAllPropertiesEquals(
        CassSetEntityByOrganization expected,
        CassSetEntityByOrganization actual
    ) {
        assertCassSetEntityByOrganizationAutoGeneratedPropertiesEquals(expected, actual);
        assertCassSetEntityByOrganizationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSetEntityByOrganizationAllUpdatablePropertiesEquals(
        CassSetEntityByOrganization expected,
        CassSetEntityByOrganization actual
    ) {
        assertCassSetEntityByOrganizationUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSetEntityByOrganizationAutoGeneratedPropertiesEquals(
        CassSetEntityByOrganization expected,
        CassSetEntityByOrganization actual
    ) {
        assertThat(expected)
            .as("Verify CassSetEntityByOrganization auto generated properties")
            .satisfies(e -> assertThat(e.getOrganizationId()).as("check organizationId").isEqualTo(actual.getOrganizationId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassSetEntityByOrganizationUpdatableFieldsEquals(
        CassSetEntityByOrganization expected,
        CassSetEntityByOrganization actual
    ) {
        assertThat(expected).as("Verify CassSetEntityByOrganization relevant properties");
    }
}
