package com.saathratri.developer.cassandra.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CassTagAsserts {

    /**
     * Asserts that the entity has all properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassTagAllPropertiesEquals(CassTag expected, CassTag actual) {
        assertCassTagAutoGeneratedPropertiesEquals(expected, actual);
        assertCassTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassTagAllUpdatablePropertiesEquals(CassTag expected, CassTag actual) {
        assertCassTagUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassTagAutoGeneratedPropertiesEquals(CassTag expected, CassTag actual) {
        assertThat(expected)
            .as("Verify CassTag auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCassTagUpdatableFieldsEquals(CassTag expected, CassTag actual) {
        assertThat(expected).as("Verify CassTag relevant properties");
    }
}
